#DefaultController

homepage:
  path: /
  defaults: {_controller: AppBundle:Default:index}


#SecurityController

login:
  path: /login
  defaults: {_controller: AppBundle:Security:login}

logout:
  path: /logout
  defaults: {_controller: AppBundle:Security:logout}




# AjaxController

getcurrentdetails:
  path: /getcurrentdaydetails
  defaults: {_controller: AppBundle:AjaxFirst:getcurrentdaydetails}