AppBundle\Entity\Adminmessage:
    type: entity
    table: adminmessage
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        message:
            type: text
            nullable: true
            length: 65535
            options:
                fixed: false
        statu:
            type: integer
            nullable: true
            options:
                unsigned: false
                default: '0'
        cdate:
            type: datetime
            nullable: true
    lifecycleCallbacks: {  }
