AppBundle\Entity\Admin:
    type: entity
    table: admin
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        musteriid:
            type: integer
            nullable: true
            options:
                unsigned: false
            column: musteriID
        name:
            type: string
            nullable: true
            length: 50
            options:
                fixed: false
        username:
            type: string
            nullable: false
            length: 50
            options:
                fixed: false
        password:
            type: string
            nullable: false
            length: 50
            options:
                fixed: false
        cdate:
            type: datetime
            nullable: true
        roles:
            type: string
            nullable: false
            length: 15
            options:
                fixed: false
        statu:
            type: integer
            nullable: false
            options:
                unsigned: false
                default: '0'
    lifecycleCallbacks: {  }
