AppBundle\Entity\Gcm:
    type: entity
    table: gcm
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        regid:
            type: text
            nullable: false
            length: 65535
            options:
                fixed: false
        kuryeid:
            type: integer
            nullable: false
            options:
                unsigned: false
            column: kuryeID
        email:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
    lifecycleCallbacks: {  }
