AppBundle\Entity\Krapp:
    type: entity
    table: krapp
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        sirketid:
            type: integer
            nullable: false
            options:
                unsigned: false
        sirketip:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
    lifecycleCallbacks: {  }
