AppBundle\Entity\Kurref01:
    type: entity
    table: kurref01
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        kayitSayisi:
            type: integer
            nullable: true
            options:
                unsigned: false
            column: kayit_sayisi
        kopruucreti:
            type: float
            nullable: true
            precision: 10
            scale: 0
            options:
                default: '2'
        kayitDegistimi:
            type: integer
            nullable: true
            options:
                unsigned: false
                default: '0'
            column: kayit_degistimi
        kuryeDurumDegisikligi:
            type: integer
            nullable: true
            options:
                unsigned: false
            column: kurye_durum_degisikligi
    lifecycleCallbacks: {  }
