AppBundle\Entity\KuryeYakitDurumu:
    type: entity
    table: kurye_yakit_durumu
    indexes:
        kurye_yakit:
            columns:
                - kurye_id
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        yakit:
            type: float
            nullable: true
            precision: 10
            scale: 0
            options:
                default: '0'
        tarih:
            type: date
            nullable: false
    manyToOne:
        kurye:
            targetEntity: Kurye01
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                kurye_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
